# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python-calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

try:
    import numpy as np
except ImportError:
    print("didnt import numpy")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowTitle("Standard Calulator")
        #MainWindow.setObjectName("Python Calculator")
        MainWindow.resize(822, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.lineEdit.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.lineEdit.setObjectName("lineEdit")

        self.user_input = []

        def display():
            #indexing = np.array(self.user_input)
            #print(self.user_input[0:])
            print()
            try:
                self.lineEdit.setText(('{}'*len(self.user_input)).format(*self.user_input))
            except SyntaxError:
                print("sep dont work")

        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setStyleSheet("background-color: rgb(11, 37, 94);")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")

        self.nine = QtWidgets.QPushButton(self.gridWidget)
        self.nine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        def nine_clicked():
            self.user_input.append(int(self.nine.text()))
            display()

        self.nine.clicked.connect(nine_clicked)

        self.nine.setMinimumSize(QtCore.QSize(80, 80))
        self.nine.setMaximumSize(QtCore.QSize(150, 16777215))
        self.nine.setBaseSize(QtCore.QSize(0, 300))


        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 1, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 1, 96))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 0, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 1, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 0, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 1, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 1, 96))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 0, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 1, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 152, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)

        self.nine.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.nine.setFont(font)
        self.nine.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.nine.setAutoDefault(False)
        self.nine.setDefault(False)
        self.nine.setFlat(False)
        self.nine.setObjectName("nine")

        self.gridLayout.addWidget(self.nine, 0, 2, 1, 1)
        self.two = QtWidgets.QPushButton(self.gridWidget)
        self.two.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def two_click():
                #print
                self.user_input.append(int(self.two.text()))
                display()
        self.two.clicked.connect(two_click)
        self.two.setMinimumSize(QtCore.QSize(80, 80))
        self.two.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 2, 1, 1, 1)
        self.seven = QtWidgets.QPushButton(self.gridWidget)
        self.seven.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        def seven_click():
                #print
                self.user_input.append(int(self.seven.text()))
                display()
        self.seven.clicked.connect(seven_click)

        self.seven.setMinimumSize(QtCore.QSize(80, 80))
        self.seven.setMaximumSize(QtCore.QSize(150, 16777215))
        self.seven.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 0, 0, 1, 1)
        self.dot = QtWidgets.QPushButton(self.gridWidget)
        self.dot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        def dot_click():
                #print
                self.user_input.append(str(self.dot.text()))
                display()
        self.dot.clicked.connect(dot_click)

        self.dot.setMinimumSize(QtCore.QSize(0, 80))
        self.dot.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.dot.setObjectName("dot")
        self.gridLayout.addWidget(self.dot, 3, 1, 1, 1)
        self.negative = QtWidgets.QPushButton(self.gridWidget)
        self.negative.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        def neg_click():
                #print
                self.user_input.append(str(self.negative.text()))
                display()
        self.negative.clicked.connect(neg_click)

        self.negative.setMinimumSize(QtCore.QSize(0, 80))
        self.negative.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.negative.setObjectName("negative")
        self.gridLayout.addWidget(self.negative, 3, 2, 1, 1)
        self.minus = QtWidgets.QPushButton(self.gridWidget)
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        def min_click():
                #print
                self.user_input.append(str(self.minus.text()))
                display()
        self.minus.clicked.connect(min_click)

        self.minus.setMinimumSize(QtCore.QSize(0, 80))
        self.minus.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 5, 101);\n"
"border: none;")
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 2, 3, 1, 1)
        self.one = QtWidgets.QPushButton(self.gridWidget)
        self.one.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        def one_click():
                #print
                self.user_input.append(int(self.one.text()))
                display()
        self.one.clicked.connect(one_click)

        self.one.setMinimumSize(QtCore.QSize(0, 80))
        self.one.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 2, 2, 1, 1)
        self.divide = QtWidgets.QPushButton(self.gridWidget)
        self.divide.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def div_click():
                #print
                self.user_input.append(str(self.divide.text()))
                display()
        self.divide.clicked.connect(div_click)
        self.divide.setMinimumSize(QtCore.QSize(150, 80))
        self.divide.setMaximumSize(QtCore.QSize(75, 100))
        self.divide.setSizeIncrement(QtCore.QSize(150, 0))
        self.divide.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.divide.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 5, 101);\n"
"border: none;")
        self.divide.setObjectName("divide")
        self.gridLayout.addWidget(self.divide, 0, 3, 1, 1)
        self.times = QtWidgets.QPushButton(self.gridWidget)
        self.times.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def times_click():
                #print
                self.user_input.append(str(self.times.text()))
                display()
        self.times.clicked.connect(times_click)
        self.times.setMinimumSize(QtCore.QSize(0, 80))
        self.times.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 5, 101);\n"
"border: none;")
        self.times.setObjectName("times")
        self.gridLayout.addWidget(self.times, 1, 3, 1, 1)
        self.eight = QtWidgets.QPushButton(self.gridWidget)
        self.eight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def eight_click():
                #print
                self.user_input.append(int(self.eight.text()))
                display()
        self.eight.clicked.connect(eight_click)
        self.eight.setMinimumSize(QtCore.QSize(0, 80))
        self.eight.setMaximumSize(QtCore.QSize(16777215, 100))
        self.eight.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 0, 1, 1, 1)
        self.four = QtWidgets.QPushButton(self.gridWidget)
        self.four.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def four_click():
                #print
                self.user_input.append(int(self.four.text()))
                display()
        self.four.clicked.connect(four_click)
        self.four.setMinimumSize(QtCore.QSize(0, 80))
        self.four.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 1, 0, 1, 1)
        self.plus = QtWidgets.QPushButton(self.gridWidget)
        self.plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def plus_click():
                #print
                self.user_input.append(str(self.plus.text()))
                display()
        self.plus.clicked.connect(plus_click)
        self.plus.setMinimumSize(QtCore.QSize(0, 80))
        self.plus.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 5, 101);\n"
"border: none;")
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 3, 3, 1, 1)
        self.five = QtWidgets.QPushButton(self.gridWidget)
        self.five.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def five_click():
                #print
                self.user_input.append(int(self.five.text()))
                display()
        self.five.clicked.connect(five_click)
        self.five.setMaximumSize(QtCore.QSize(150, 200))
        self.five.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 1, 1, 1, 1)
        self.three = QtWidgets.QPushButton(self.gridWidget)
        self.three.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def tree_click():
                #print
                self.user_input.append(int(self.three.text()))
                display()
        self.three.clicked.connect(tree_click)
        self.three.setMinimumSize(QtCore.QSize(0, 80))
        self.three.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 2, 0, 1, 1)
        self.zero = QtWidgets.QPushButton(self.gridWidget)
        self.zero.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def zero_click():
                #print
                self.user_input.append(int(self.zero.text()))
                display()
        self.zero.clicked.connect(zero_click)
        self.zero.setMinimumSize(QtCore.QSize(0, 80))
        self.zero.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 3, 0, 1, 1)
        self.six = QtWidgets.QPushButton(self.gridWidget)
        self.six.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def six_click():
                #print
                self.user_input.append(int(self.six.text()))
                display()
        self.six.clicked.connect(six_click)
        self.six.setEnabled(True)
        self.six.setMaximumSize(QtCore.QSize(200, 9999999))
        self.six.setSizeIncrement(QtCore.QSize(0, 130))
        self.six.setBaseSize(QtCore.QSize(10, 80))
        self.six.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"background-color: rgb(27, 152, 228);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def equal_click():
                #print
                print("yoink")
                this_thing = eval(self.lineEdit.text())
                self.lineEdit.setText(f'{this_thing}')
                print(this_thing)
        self.pushButton.clicked.connect(equal_click)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 5, 101);\n"
"border: none;")
        self.pushButton.setObjectName("pushButton")

        self.gridLayout.addWidget(self.pushButton, 4, 3, 1, 1)

        self.clear = QtWidgets.QPushButton(self.gridWidget)
        self.clear.setText("CLEAR")
        self.clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        def clear_out():
                self.lineEdit.setText(" ")
                self.user_input.clear()
        clear_out()
        self.clear.clicked.connect(clear_out)
        self.clear.setMinimumSize(80, 80)
        self.clear.setStyleSheet("font: 20pt \"Segoe UI\";\n" 
        "color: rgb(255, 255, 255);\n" 
        "background-color: rgb(255,5,101);\n"
        "border: none;")
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 4, 2, 1, 1)

        self.gridLayout.setColumnStretch(0, 30)
        self.gridLayout_2.addWidget(self.gridWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCalculator = QtWidgets.QAction(MainWindow)
        self.actionCalculator.setObjectName("actionCalculator")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionUsage = QtWidgets.QAction(MainWindow)
        self.actionUsage.setObjectName("actionUsage")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCalculator)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionUsage)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.two, self.negative)
        MainWindow.setTabOrder(self.negative, self.three)
        MainWindow.setTabOrder(self.three, self.times)
        MainWindow.setTabOrder(self.times, self.six)
        MainWindow.setTabOrder(self.six, self.five)
        MainWindow.setTabOrder(self.five, self.four)
        MainWindow.setTabOrder(self.four, self.nine)
        MainWindow.setTabOrder(self.nine, self.eight)
        MainWindow.setTabOrder(self.eight, self.seven)
        MainWindow.setTabOrder(self.seven, self.dot)
        MainWindow.setTabOrder(self.dot, self.zero)
        MainWindow.setTabOrder(self.zero, self.minus)
        MainWindow.setTabOrder(self.minus, self.plus)
        MainWindow.setTabOrder(self.plus, self.one)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Calculator"))
        self.lineEdit.setText(_translate("MainWindow", ""))
        self.nine.setText(_translate("MainWindow", "9"))
        self.two.setText(_translate("MainWindow", "2"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.dot.setText(_translate("MainWindow", "."))
        self.negative.setText(_translate("MainWindow", "-"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.one.setText(_translate("MainWindow", "1"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.times.setText(_translate("MainWindow", "*"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.four.setText(_translate("MainWindow", "4"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.five.setText(_translate("MainWindow", "5"))
        self.three.setText(_translate("MainWindow", "3"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.six.setText(_translate("MainWindow", "6"))
        self.pushButton.setText(_translate("MainWindow", "="))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCalculator.setText(_translate("MainWindow", "Calculator"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionUsage.setText(_translate("MainWindow", "Usage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    #MainWindow.setWindowTitle("calculatrroooo")
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
